### ISSUE TITLE
Examples only cover lower-left corner of Pyglet window

### ISSUE THREAD

**Issue by akx** [szabolcsdombi/zengl#19]
Broke this out of #18.

The examples only cover the lower-left corner of the Pyglet window:

<img width="1280" alt="Screenshot 2022-06-02 at 21 15 04" src="https://user-images.githubusercontent.com/58669/171698649-40066cea-151e-4e61-b82c-7bbcbc5a4bde.png">
<img width="1280" alt="Screenshot 2022-06-02 at 21 18 38" src="https://user-images.githubusercontent.com/58669/171699188-b6e0a623-cb0b-4bfc-9178-6d30e6890cad.png">

Other output, such as the mp4 generated by `ffmpeg_stream.py` are just fine (1280x720).

---
Python 3.9.12 on macOS 10.15.7 on AMD Radeon Pro 5500M 4 GB graphics (macbook pro 2019), libraries:
```
ffmpeg-python==0.2.0
glcontext==2.3.6
moderngl==5.6.4
Pillow==9.1.1
pyglet==1.5.26
```

**Comment by akx** [comment]
Just got back to the office and was about to report that this isn't an issue on the external LoDPI screen :) I'll try out the PR!

**Comment by szabolcsdombi** [comment]
so #20 does not resolve the issue?

**Comment by szabolcsdombi** [comment]
the examples are not resizable as it would require extra logic that is out of the scope of the basic examples.
however, I plan to add examples for resizable windows too.
