### ISSUE TITLE
Rendering Dear ImGui from Vertex Buffers

### ISSUE THREAD

**Issue by Aman-Anas** [szabolcsdombi/zengl#50]
I was thinking of trying to integrate pyimgui with zengl's web integration (which seems to use pyodide). Hopefully this would allow me to easily make web-based GUIs with imgui (maybe even for mobile devices via the browser). Pyimgui outputs a vertex buffer for openGL or any other rendering framework to render, and the relevant code from the built-in pyopengl integration looks like this (from here: https://github.com/pyimgui/pyimgui/blob/master/imgui/integrations/opengl.py)
```python
        gl.glUseProgram(self._shader_handle)
        gl.glUniform1i(self._attrib_location_tex, 0)
        gl.glUniformMatrix4fv(self._attrib_proj_mtx, 1, gl.GL_FALSE, ortho_projection)
        gl.glBindVertexArray(self._vao_handle)

        for commands in draw_data.commands_lists:
            idx_buffer_offset = 0

            gl.glBindBuffer(gl.GL_ARRAY_BUFFER, self._vbo_handle)
            # todo: check this (sizes)
            gl.glBufferData(gl.GL_ARRAY_BUFFER, commands.vtx_buffer_size * imgui.VERTEX_SIZE, ctypes.c_void_p(commands.vtx_buffer_data), gl.GL_STREAM_DRAW)

            gl.glBindBuffer(gl.GL_ELEMENT_ARRAY_BUFFER, self._elements_handle)
            # todo: check this (sizes)
            gl.glBufferData(gl.GL_ELEMENT_ARRAY_BUFFER, commands.idx_buffer_size * imgui.INDEX_SIZE, ctypes.c_void_p(commands.idx_buffer_data), gl.GL_STREAM_DRAW)

            # todo: allow to iterate over _CmdList
            for command in commands.commands:
                gl.glBindTexture(gl.GL_TEXTURE_2D, command.texture_id)

                # todo: use named tuple
                x, y, z, w = command.clip_rect
                gl.glScissor(int(x), int(fb_height - w), int(z - x), int(w - y))

                if imgui.INDEX_SIZE == 2:
                    gltype = gl.GL_UNSIGNED_SHORT
                else:
                    gltype = gl.GL_UNSIGNED_INT

                gl.glDrawElements(gl.GL_TRIANGLES, command.elem_count, gltype, ctypes.c_void_p(idx_buffer_offset))

                idx_buffer_offset += command.elem_count * imgui.INDEX_SIZE

        # restore modified GL state
        restore_common_gl_state(common_gl_state_tuple)

        gl.glUseProgram(last_program)
```
I was wondering if glDrawElements() works the same in zengl, and maybe if there's any examples of vertex buffers? I am not particularly opengl experienced.

**Comment by szabolcsdombi** [comment]
Hi, this is mostly possible with ZenGL and it would work out of the box on the web.

The only issue is that ZenGL does not maintain the scissor box.
Also ZenGL builds around the idea of knowing the resources ahead of the time so during the draw commands newly discovered textures need new pipelines (lightweight objects).
Usually there is just one texture in imgui, that is the atlas.

From a high level it would look as follows:

```py
for commands in draw_data.commands_lists:
    vbo.write(...)
    ibo.write(...)
    for command in commands.commands:
        # set scissor command.clip_rect without ZenGL
        pipeline = get_or_build_pipeline(command.texture_id)
        pipeline.vertex_count = command.elem_count
        pipeline.first_vertex = idx_buffer_offset
        pipeline.render()
```

I think rendering imgui this way would be unnecessarily complicated.

Imgui works really well as the final step rendering step. To support this alongside ZenGL.
The structure should be the following.

```py
ctx.new_frame()
# zengl scene
ctx.end_frame()
imgui_opengl_calls()
```

It is important to have imgui after `ctx.end_frame()` which disables G_FRAMEBUFFER_SRGB (a flag that imgui does not handle well)

To get imgui working in the browser with pyodide, you have to implement the code you pasted with WebGL2 (which will be mostly the same) and in the Pyodide case gl should be js proxy.

ZenGL uses a similar technique to setup a WebGL2 backend.

Here is a pure Python code that works out of the bost with the latest Pyodide version:

```py
import struct

import js
import pyodide
import pyodide_js
import zengl

js.document.getElementById('loading').remove()
js.document.getElementsByClassName('terminal')[0].style.backgroundColor = 'transparent'
js.document.getElementsByClassName('terminal')[0].style.textShadow = 'black 1px 1px 1px, black 1px 1px 0'

width = js.window.innerWidth
height = js.window.innerHeight

canvas = js.document.createElement('canvas')
canvas.style.position = 'fixed'
canvas.style.top = '0'
canvas.style.left = '0'
canvas.style.width = width
canvas.style.height = width
canvas.width = width
canvas.height = height
canvas = js.document.body.insertBefore(canvas, js.document.body.children[0])

gl = canvas.getContext(
    'webgl2',
    powerPreference='high-performance',
    premultipliedAlpha=False,
    antialias=False,
    alpha=False,
    depth=False,
    stencil=False,
)

setup_gl = js.eval(zengl.setup_gl)
setup_gl(pyodide_js._module, gl)

ctx = zengl.context()
```

The code if from [pyodide-water-background](https://github.com/szabolcsdombi/pyodide-water-background)

---

I think the best solution is to get first imgui working with the gl object from above.
Then, if you need ZenGL just call it before imgui draws.

**Comment by szabolcsdombi** [comment]
needs a bit of polish

![image](https://github.com/szabolcsdombi/zengl/assets/11232402/6191a45b-2cdb-4373-9d3d-a1ab445c96c3)

**Comment by szabolcsdombi** [comment]
Closing this for now.
Basically the rendering part is easy to achieve, however the user input handling must be connected manually with the event listeners. This will be the responsibility of the window implementation rather than this rendering library.

**Comment by pbk0** [comment]
Any pointers for window implementation. I miss this feature. I hope there is opensource project for this.
