### ISSUE TITLE
Fails with Cannot detect window with OpenGL support

### ISSUE THREAD

**Issue by BinaryWarlock** [szabolcsdombi/zengl#57]
On Linux with proprietary NVidia drivers and X11:

```
  File "/home/code/venv/lib/python3.10/site-packages/_zengl.py", line 279, in __init__
    raise RuntimeError('Cannot detect window with OpenGL support')
RuntimeError: Cannot detect window with OpenGL support
```

This happens with both headless (EGL) and GLX (X11), on the fractal.py example.

This doesn't happen with other GL applications -- glxgears, browsers, and other such applications have always worked just fine.

Is it possible to get an error code out of `glcontext` to see if and why the context creation is failing?

**Comment by szabolcsdombi** [comment]
The mixed egl/x11 support is a recent change are you on the latest version with zengl? It should be 2.4.0

The headless examples still use glcontext.

I have a glcontext update in progress. The code is already in the repo under the glcontext/headless.cpp it is not enabled because it does not build within cibuildwheel.

**Comment by BinaryWarlock** [comment]
Yes, I'm on zengl 2.4.0.

zengl's `DefaultLoader` always tries to use libEGL first, so if it loads `libEGL.so` and `eglGetCurrentContext` fails it won't even try to use `libGL.so`.

In my case, forcing it to use `libGL.so` works for both headless and windowed:
```python
        elif sys.platform.startswith('linux'):
            try:
                """
                lib = ctypes.CDLL('libEGL.so')
                proc = ctypes.cast(lib.eglGetProcAddress, ctypes.CFUNCTYPE(ctypes.c_ulonglong, ctypes.c_char_p))
                if not lib.eglGetCurrentContext():
                    raise RuntimeError('Cannot detect window with OpenGL support')

                def loader(name):
                    return proc(name.encode())
                """
                raise OSError()

            except OSError:
                lib = ctypes.CDLL('libGL.so')
                proc = ctypes.cast(lib.glXGetProcAddress, ctypes.CFUNCTYPE(ctypes.c_ulonglong, ctypes.c_char_p))
                if not lib.glXGetCurrentContext():
                    raise RuntimeError('Cannot detect window with OpenGL support') from None

                def loader(name):
                    return proc(name.encode()) or funcptr(lib, name)
```

I'm not sure why that is, but both examples work now.

**Comment by szabolcsdombi** [comment]
Wait this is a bug. The except branch should not have the OSError in it. It should capture the Runtime error raised manually. I thi k i made a mistake when run some automatic code fixing

**Comment by szabolcsdombi** [comment]
2.4.1 should be out and should solve the problem, can you confirm it?

**Comment by BinaryWarlock** [comment]
Yes, 2.4.1 works for me now. Thank you.
