### ISSUE TITLE
`zengl` doesn't seem to want to work on OpenGL ES (or at least not ANGLE)

### ISSUE THREAD

**Issue by jonathanhogg** [szabolcsdombi/zengl#59]
I've just been playing with the idea of using `zengl` on macOS with ANGLE as the underlying OpenGL (ES) implementation. As OpenGL is deprecated on macOS, it's actually faster (in my limited testing) to use ANGLE's translation to Metal than to use Apple's aged OpenGL framework – especially so on Apple Silicon.

Anyways, I've managed to get it working using a custom loader that loads `libEGL.dylib` (cribbed from inside `Google Chrome.app` along with `libGLESv2.dylib` as I was too lazy to build ANGLE) and then pokes that instead and it pretty much works except that `zengl` wants to use the `glGetBufferSubData()` function and this doesn't seem to be implemented in OpenGL ES.

Apparently on OpenGL ES one is supposed to use [`glMapBufferRange()`](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glMapBufferRange.xhtml) – although I am no expert on this and so can't confirm.

If I just comment out all of the references to `glGetBufferSubData()` in `_zen.c` I can get a basic triangle example working.

I've got this hacked into a fork at the moment if you want to take a look:

https://github.com/jonathanhogg/zengl

**Comment by szabolcsdombi** [comment]
I know about this issue, i solve it by implementing the loader to return an implementation for that function. No need to change zengl itself.

You have two simpler solutions:

- Implement getbuffersubdata as a noop.
- Implemenr using mapbuffer memcpy unmapbuffer.

I will paste my code here when i get to my computer.
Both can be done from python at runtime.

**Comment by szabolcsdombi** [comment]
this is what I found in my my backups:

```py
@ctypes.WINFUNCTYPE(None, ctypes.c_int, ctypes.c_size_t, ctypes.c_size_t, ctypes.c_void_p)
def glGetBufferSubData(target, offset, size, data):
    pass

class Loader:
    def load_opengl_function(self, name):
        if name == 'glGetBufferSubData':
            return ctypes.cast(glGetBufferSubData, ctypes.c_void_p).value
        return ctypes.cast(egl[name], ctypes.c_void_p).value

zengl.init(Loader())
```

a better solution uses `zengl.loader()` a similar class to Loader as the default return value.
for linux/mac also `WINFUNCTYPE` should be `CFUNCTION`

I hope this helps by the time I post a proper solution.

**Comment by jonathanhogg** [comment]
Ah! Of course! I never though to monkey-patch it in the loader…

I'm still experimenting with `zengl` at the moment as all of my current code uses `moderngl`. I have to decide whether to make the switch or figure out how to patch `glcontext` to work with ANGLE – I've made a stab at this but have so far only gotten as far as a context that reports correctly and then explodes when I try to run a shader 😂

**Comment by szabolcsdombi** [comment]
This loader should work with moderngl too.
However moderngl 5.9 and 5.10 still has compatibility issues with gles. The blocker to fixing them cause bugs for existing users just as reported multiple times recently about fbo.clear.
To pass this loader to moderngl use the new init_context function with get_context later on.
Or pass it as backend=... to create_context.

Please let me know if you find any blockers using zengl.

**Comment by szabolcsdombi** [comment]
Added an example code for ANGLE.
My code was tested with a custom angle build with a vulkan backend set.
I think it has nothing specific to that in the code.
I will port this to macos the next time I boot up a related device.

https://github.com/szabolcsdombi/zengl/blob/main/examples/experimental/angle_backend.py

Changes to port this to linux/mac should be trivial.

**Comment by jonathanhogg** [comment]
Ta for this. I also didn't realise that you can pass your own loader into `moderngl`. Now that I dig into the code I can see the undocumented `init_context()` function.

I've tried a custom EGL loader but, yes, `moderngl` seems to dislike it in other ways, which is odd because I have successfully run my code on an ARM64 Linux machine that *only* has OpenGL ES available…

Anyways, thanks for your help. I will try to find the time to do some more playing around with `zengl` and see how hard it would be to swap out `moderngl`.

**Comment by szabolcsdombi** [comment]
ZenGL is 100% compatible with GLES, ModernGL gives you access to extensions like SSBO, texture handles, compute shader, geom shader ...

I usually just use the gles compatible subset of OpenGL this is why i made ZenGL.
