### ISSUE TITLE
just getting started, using streaming_video.py example

### ISSUE THREAD

**Issue by bsenftner** [szabolcsdombi/zengl#7]
Realizing what I'm looking for may not be in zengl; when I run the streaming_video.py example I see my webcam0 fine, but it is vertically flipped. 

To vertically flip the video frame, would that be done at the imageio, the zengl, or some other image module level I need to bring into that minimal example? I am thinking the return value from zengl.rgba(next(it), 'rgb') would saved to an intermediate variable, potentially as input to some image object that allows basic graphical operations, such as the vertical flip I want?

**Comment by szabolcsdombi** [comment]
You can flip it with `zengl.rgba(next(it)[::-1].tobytes(), 'rgb')`

`next(it)` is actually a numpy array

`zengl.rgba(...)` is a very limited helper to provide a readable way to express rbg to rgba conversion or similar.

you can do the conversion and padding completely with **numpy** as a single step:

```py
import numpy as np
rgba = np.zeros((height, width, 4), 'u1')

while window.update():
    rgba[:, :, :3] = next(it)[::-1]
    image.write(rgba)
    ...
```

**Comment by bsenftner** [comment]
Makes perfect sense, thanks.
